package uk.gov.hmcts.opal.common.contentdigest;

import lombok.Getter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.bind.ConstructorBinding;

import java.util.Map;

@ConfigurationProperties(prefix = "opal.common.content-digest")
@Getter
public class ContentDigestProperties {

    private static final Map<String, String> DEFAULT_SUPPORTED_ALGORITHMS = Map.of("sha-512", "SHA-512");
    private static final String DEFAULT_RESPONSE_ALGORITHM = "SHA-512";

    private final Map<String, String> supportedAlgorithms;
    private final Request request;
    private final Response response;

    @ConstructorBinding
    public ContentDigestProperties(Map<String, String> supportedAlgorithms, Request request, Response response) {
        this.supportedAlgorithms = supportedAlgorithms == null || supportedAlgorithms.isEmpty()
            ? DEFAULT_SUPPORTED_ALGORITHMS : Map.copyOf(supportedAlgorithms);
        this.request = request == null ? new Request(null, null) : request;
        this.response = response == null ? new Response(null, null) : response;
    }

    @Getter
    public static class Request {

        private final boolean enforce;
        private final boolean autoGenerate;

        @ConstructorBinding
        public Request(Boolean enforce, Boolean autoGenerate) {
            this.enforce = enforce != null && enforce;
            this.autoGenerate = autoGenerate != null && autoGenerate;
        }

        public boolean isEnforced() {
            return enforce;
        }

        public boolean isAutoGenerated() {
            return autoGenerate;
        }
    }

    @Getter
    public static class Response {

        private final boolean enforce;
        private final String algorithm;

        @ConstructorBinding
        public Response(Boolean enforce, String algorithm) {
            this.enforce = enforce != null && enforce;
            this.algorithm = algorithm == null || algorithm.isBlank() ? DEFAULT_RESPONSE_ALGORITHM : algorithm;
        }

        public boolean isEnforced() {
            return enforce;
        }
    }
}
