package uk.gov.hmcts.opal.common.contentdigest;

import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.util.TestPropertyValues;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.mock.web.MockFilterChain;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import uk.gov.hmcts.opal.common.controllers.advice.OpalGlobalExceptionHandler;

import java.security.MessageDigest;
import java.util.Base64;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;

class ContentDigestConfigurationTest {

    @Test
    void configurationCreatesReusableBeansWithDefaultProperties() {
        try (AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext()) {
            context.register(ContentDigestConfiguration.class);
            context.refresh();

            assertNotNull(context.getBean(ContentDigestProperties.class));
            assertNotNull(context.getBean(ContentDigestValidatorInterceptor.class));
            assertNotNull(context.getBean(WebMvcConfigurer.class));
            assertNotNull(context.getBean(RequestCachingFilter.class));
            assertNotNull(context.getBean(ContentDigestResponseFilter.class));

            ContentDigestProperties properties = context.getBean(ContentDigestProperties.class);
            assertThat(properties.getSupportedAlgorithms()).containsExactlyEntriesOf(Map.of("sha-512", "SHA-512"));
            assertThat(properties.getRequest().isEnforced()).isFalse();
            assertThat(properties.getRequest().isAutoGenerated()).isFalse();
            assertThat(properties.getResponse().isEnforced()).isFalse();
            assertThat(properties.getResponse().getAlgorithm()).isEqualTo("SHA-512");
        }
    }

    @Test
    void configurationCreatesReusableBeans() {
        try (AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext()) {
            TestPropertyValues.of("opal.common.content-digest.request.enforce=true",
                "opal.common.content-digest.request.auto-generate=false",
                "opal.common.content-digest.supported-algorithms.sha-512=SHA-512",
                "opal.common.content-digest.response.enforce=false",
                "opal.common.content-digest.response.algorithm=SHA-512")
                .applyTo(context);
            context.register(ContentDigestConfiguration.class);
            context.refresh();

            assertNotNull(context.getBean(ContentDigestProperties.class));
            assertNotNull(context.getBean(ContentDigestValidatorInterceptor.class));
            assertNotNull(context.getBean(WebMvcConfigurer.class));
            assertNotNull(context.getBean(RequestCachingFilter.class));
            assertNotNull(context.getBean(ContentDigestResponseFilter.class));

            ContentDigestProperties properties = context.getBean(ContentDigestProperties.class);
            assertThat(properties.getSupportedAlgorithms()).containsEntry("sha-512", "SHA-512");
            assertThat(properties.getRequest().isEnforced()).isTrue();
            assertThat(properties.getRequest().isAutoGenerated()).isFalse();
            assertThat(properties.getResponse().isEnforced()).isFalse();
            assertThat(properties.getResponse().getAlgorithm()).isEqualTo("SHA-512");
        }
    }

    @Test
    void opalGlobalExceptionHandlerHandlesContentDigestExceptions() {
        OpalGlobalExceptionHandler handler = new OpalGlobalExceptionHandler();

        assertNotNull(handler.handleInvalidContentDigestException(
            new InvalidContentDigestException("Digest validation failed", "Invalid digest")
        ));
    }

    @Test
    void addInterceptors_addsContentDigestValidatorInterceptor() {
        ContentDigestConfiguration configuration = new ContentDigestConfiguration();
        ContentDigestValidatorInterceptor interceptor = mock(ContentDigestValidatorInterceptor.class);
        InterceptorRegistry registry = mock(InterceptorRegistry.class);

        configuration.contentDigestWebMvcConfigurer(interceptor).addInterceptors(registry);

        verify(registry).addInterceptor(interceptor);
        verifyNoMoreInteractions(registry);
    }

    @Test
    void configurationProvidesCachingFilterRequiredByInterceptor() throws Exception {
        try (AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext()) {
            TestPropertyValues.of("opal.common.content-digest.request.auto-generate=false",
                "opal.common.content-digest.supported-algorithms.sha-512=SHA-512",
                "opal.common.content-digest.response.enforce=true",
                "opal.common.content-digest.response.algorithm=SHA-512")
                .applyTo(context);
            context.register(ContentDigestConfiguration.class);
            context.refresh();

            String body = "request-body";
            MockHttpServletRequest request = new MockHttpServletRequest();
            request.setContent(body.getBytes());
            request.addHeader(ContentDigestValidatorInterceptor.CONTENT_DIGEST, contentDigestHeaderFor(body));
            MockHttpServletResponse response = new MockHttpServletResponse();
            ContentDigestValidatorInterceptor interceptor = context.getBean(ContentDigestValidatorInterceptor.class);
            MockFilterChain filterChain = new MockFilterChain() {
                @Override
                public void doFilter(ServletRequest request, ServletResponse response) {
                    assertThat(request).isInstanceOf(CachedBodyHttpServletRequest.class);
                    assertThat(interceptor.preHandle((CachedBodyHttpServletRequest) request,
                                                     (MockHttpServletResponse) response,
                                                     null)).isTrue();
                }
            };

            context.getBean(RequestCachingFilter.class).doFilter(request, response, filterChain);
        }
    }

    private static String contentDigestHeaderFor(String body) throws Exception {
        MessageDigest messageDigest = MessageDigest.getInstance("SHA-512");
        String digest = Base64.getEncoder().encodeToString(messageDigest.digest(body.getBytes()));
        return "sha-512=:" + digest + ":";
    }
}
